name: build-and-test

on:
  push:
    branches:
      - main
    paths:
      - '*'
  pull_request:
    branches:
      - '*'
    paths:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - run: |
          sudo apt update && \
          sudo apt install \
              curl

      - run: |
          cargo fmt -- --check

      - run: |
          cargo clippy -- --no-deps -D warnings

      - run: |
          cargo test

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - run: |
          ./scripts/e2e-test.sh
