[workspace]
members = [
    "apps/handcraft",
    "apps/gesha",
    "examples/v3_0",
]
resolver = "2"

[workspace.dependencies]
async-trait = "0.1.71"
opentelemetry = { version = "0.19.0", default-features = false, features = ["trace", "rt-tokio", "metrics"] }
pretty_assertions = "1.4.0"
serde = { version = "1.0.169", features = ["derive"] }
serde_json = "1.0.100"
tokio = { version = "1.29.1", features = ["full"] }
tracing = "0.1"
