[workspace]
members = [
    "apps/handcraft",
    "apps/gesha",
    "examples/v3_0",
]

[workspace.dependencies]
async-trait = "0.1.61"
pretty_assertions = "1.3.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
