[workspace]
members = [
    "apps/handcraft",
    "apps/gesha",
    "examples/v3_0",
]

[workspace.dependencies]
async-trait = "0.1.68"
opentelemetry = { version = "0.18.0", default-features = false, features = ["trace", "rt-tokio", "metrics"] }
pretty_assertions = "1.3.0"
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"
tokio = { version = "1.27.0", features = ["full"] }
tracing = "0.1"
