[workspace]
members = [
    "apps/handcraft",
    "apps/gesha",
    "apps/gesha-test",
    "examples/v3_0",
]
resolver = "2"

[workspace.dependencies]
async-trait = "0.1.73"
clap = { version = "4.4.6", features = ["derive"] }
opentelemetry = { version = "0.21.0", default-features = false, features = ["trace", "metrics"] }
pretty_assertions = "1.4.0"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
tokio = { version = "1.32.0", features = ["full"] }
tracing = "0.1"
