version: '3'

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.81.0
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"

  # https://www.jaegertracing.io/docs/next-release/getting-started/
  jaeger:
    image: jaegertracing/all-in-one:1.47.0
    ports:
      - "16686:16686"
