# https://release-plz.dev/docs/config

[workspace]
allow_dirty = true
release = false
publish = false

[[package]]
name = "gesha"
publish = true
release = true

[[package]]
name = "gesha-verify"
dependencies_update = true

[[package]]
name = "openapi-types"
publish = true
release = true

[[package]]
name = "gesha-core"
publish = true
release = true

[[package]]
name = "gesha-rust-shapes"
publish = true
release = true

[[package]]
name = "gesha-rust-types"
publish = true
release = true
