# https://release-plz.dev/docs/config

[workspace]
release = false
publish = false
pr_labels = ["release"]

[[package]]
name = "gesha"
publish = true
release = true
changelog_include = [
    "openapi-types",
    "gesha-core",
    "gesha-rust-shapes",
    "gesha-rust-types",
]

[[package]]
name = "openapi-types"
publish = true
release = true

[[package]]
name = "gesha-collections"
publish = true
release = true

[[package]]
name = "gesha-core"
publish = true
release = true

[[package]]
name = "gesha-rust-shapes"
publish = true
release = true

[[package]]
name = "gesha-rust-types"
publish = true
release = true

[[package]]
name = "gesha-macros"
publish = true
release = true
