/*
    Generated by gesha command; DO NOT EDIT BY HAND!
*/
pub mod all_of;
pub mod all_of_inline_all_of;
pub mod all_of_inline_array;
pub mod all_of_override_fields;
pub mod all_of_override_optional;
pub mod all_of_ref;
pub mod array;
pub mod boolean_field;
pub mod camel_case_fields;
pub mod enums;
pub mod newtype;
pub mod newtype_numeric;
pub mod nullable_field;
pub mod numeric_fields;
pub mod object_inline;
pub mod object_inline_all_of;
pub mod object_inline_enum;
pub mod object_inline_nested;
pub mod object_inline_nullable;
pub mod object_inline_one_of;
pub mod object_inline_ref;
pub mod object_simple;
pub mod one_of;
pub mod optional_field;
pub mod ref_items;
pub mod ref_property;
pub mod reserved_keywords;
pub mod title_description;
