/*
    Generated by gesha command; DO NOT EDIT BY HAND!
*/
pub mod all_of;
pub mod all_of_ref;
pub mod array;
pub mod boolean_field;
pub mod camel_case_fields;
pub mod enums;
pub mod newtype;
pub mod newtype_numeric;
pub mod nullable_field;
pub mod numeric_fields;
pub mod object_simple;
pub mod optional_field;
pub mod ref_items;
pub mod ref_property;
pub mod reserved_keywords;
pub mod title_description;
