/*
    Generated by gesha command; DO NOT EDIT BY HAND!
*/
pub mod schemas {
    use serde::Deserialize;
    use serde::Serialize;

    #[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
    pub struct IntegerDefaultValue(i64);
    impl From<i64> for IntegerDefaultValue {
        fn from(x: i64) -> IntegerDefaultValue {
            Self(x)
        }
    }

    #[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
    pub struct Int64Value(i64);
    impl From<i64> for Int64Value {
        fn from(x: i64) -> Int64Value {
            Self(x)
        }
    }

    #[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
    pub struct Int32Value(i32);
    impl From<i32> for Int32Value {
        fn from(x: i32) -> Int32Value {
            Self(x)
        }
    }

    #[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
    pub struct NumberDefaultValue(f64);
    impl From<f64> for NumberDefaultValue {
        fn from(x: f64) -> NumberDefaultValue {
            Self(x)
        }
    }

    #[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
    pub struct FloatValue(f32);
    impl From<f32> for FloatValue {
        fn from(x: f32) -> FloatValue {
            Self(x)
        }
    }

    #[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
    pub struct DoubleValue(f64);
    impl From<f64> for DoubleValue {
        fn from(x: f64) -> DoubleValue {
            Self(x)
        }
    }
}
