/*
    Generated by gesha command; DO NOT EDIT BY HAND!
*/
pub mod schemas {
    use serde::Deserialize;
    use serde::Serialize;

    #[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
    pub struct StringValue(String);
    impl From<String> for StringValue {
        fn from(x: String) -> StringValue {
            Self(x)
        }
    }

    #[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
    pub struct BooleanValue(bool);
    impl From<bool> for BooleanValue {
        fn from(x: bool) -> BooleanValue {
            Self(x)
        }
    }

    #[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
    pub struct ArrayValue(Vec<i64>);
    impl From<Vec<i64>> for ArrayValue {
        fn from(x: Vec<i64>) -> ArrayValue {
            Self(x)
        }
    }

    #[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
    pub struct ArrayCustomValue(Vec<Pet>);
    impl From<Vec<Pet>> for ArrayCustomValue {
        fn from(x: Vec<Pet>) -> ArrayCustomValue {
            Self(x)
        }
    }

    #[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
    pub struct Pet {
        pub id: i64,
    }
}
