/*
    Generated by gesha command; DO NOT EDIT BY HAND!
*/
pub mod schemas {
    use super::core::Patch;
    use serde::Deserialize;
    use serde::Serialize;

    #[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
    pub struct Sample1 {
        pub x1: Patch<String>,
    }
}

pub mod core {
    use serde::Deserialize;
    use serde::Serialize;

    #[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
    pub struct Patch<A>(A);
}
