/*
    Generated by gesha command; DO NOT EDIT BY HAND!
*/
pub mod schemas {
    use serde::Deserialize;
    use serde::Serialize;

    /**
    Pet
    */
    #[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
    pub struct OnlyTitle {
        pub id: i64,
    }

    /**
    A pet for sale in the pet store
    */
    #[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
    pub struct OnlyDescription {
        pub id: i64,
    }

    /**
    Pet

    A pet for sale in the pet store
    */
    #[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
    pub struct TitleAndDescription {
        pub id: i64,
    }
}
