[package]
name = "gesha"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gesha-core = { path = "../../libs/gesha-core" }
openapi-types = { path = "../../libs/openapi-types" }
clap = { version = "4.0.26", features = ["derive"] }
