[package]
name = "gesha"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "gesha-test"
path = "src/gesha-test.rs"

[dependencies]
gesha-core = { path = "../../libs/gesha-core" }
openapi-types = { path = "../../libs/openapi-types" }

clap = { version = "4.1.1", features = ["derive"] }
opentelemetry = { version = "0.18.0", default-features = false, features = ["trace", "rt-tokio", "metrics"] }
opentelemetry-otlp = { version = "0.11.0", features = ["metrics"] }
tokio = { version = "1.25.0", features = ["full"] }
tracing-opentelemetry = { version = "0.18", features = ["metrics"] }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
