/*
    Generated by gesha command; DO NOT EDIT BY HAND!
*/
pub mod schemas {
    use serde::Deserialize;
    use serde::Serialize;

    #[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
    pub struct Base {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub x1: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub x2: Option<i64>,
    }

    #[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
    pub struct Extended {
        pub x1: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub x2: Option<i64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub foo: Option<String>,
    }

    #[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
    pub struct ExtendedMore {
        pub x1: String,
        pub x2: i64,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub foo: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub bar: Option<i64>,
    }
}
