/*
    Generated by gesha command; DO NOT EDIT BY HAND!
*/
pub mod schemas {
    use serde::Deserialize;
    use serde::Serialize;

    #[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
    pub struct NumberList(Vec<number_list::NumberListItem>);
    impl From<Vec<number_list::NumberListItem>> for NumberList {
        fn from(this: Vec<number_list::NumberListItem>) -> Self {
            Self(this)
        }
    }
    impl From<NumberList> for Vec<number_list::NumberListItem> {
        fn from(this: NumberList) -> Self {
            this.0
        }
    }

    pub mod number_list {
        use serde::Deserialize;
        use serde::Serialize;

        #[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
        pub struct NumberListItem {
            #[serde(default, skip_serializing_if = "Option::is_none")]
            pub a1: Option<f64>,
        }
    }
}
