/*
    Generated by gesha command; DO NOT EDIT BY HAND!
*/
pub mod schemas {

    #[derive(Clone, Debug, PartialEq)]
    pub enum IntEnum {
        _0,
        _100,
        _200,
    }

    gesha_macros::impl_enum_serde!(IntEnum {
        i64: [(_0, 0)],
        u64: [(_100, 100), (_200, 200)],
    });

    gesha_macros::impl_enum_from!(
        IntEnum,
        super::core::Error,
        [i32],
        [(_0, 0), (_100, 100), (_200, 200)],
    );
}

pub mod core {
    #[derive(Debug)]
    pub enum Error {
        UnknownEnumValue {
            enum_name: &'static str,
            value: String,
        },
    }
}
