/*
    Generated by gesha command; DO NOT EDIT BY HAND!
*/
pub mod schemas {
    #[derive(Clone, Debug, PartialEq)]
    pub enum MixedTypeEnum {
        _1000,
        _2000,
        _2001,
        _2002,
        Minus42,
    }

    gesha_macros::impl_enum!(MixedTypeEnum {
        u64: [(_1000, 1000)],
        str: [(_2000, "2000"), (_2001, "2001"), (_2002, "2002")],
        i64: [(Minus42, -42)],
    });
}
