/*
    Generated by gesha command; DO NOT EDIT BY HAND!
*/
pub mod schemas {
    #[derive(Clone, Debug, PartialEq)]
    pub enum IntEnum {
        _0,
        _100,
        _200,
    }

    gesha_macros::impl_enum!(
        impl Serialize,
        impl Deserialize,
        IntEnum {
            i64: [(_0, 0)],
            u64: [(_100, 100), (_200, 200)],
        },
    );

    gesha_macros::impl_enum!(
        impl From<IntEnum>,
        impl TryFrom<i32>,
        super::core::Error,
        [(_0, 0), (_100, 100), (_200, 200)],
    );
}

pub mod core {
    #[derive(Debug)]
    pub enum Error {
        UnknownEnumValue {
            enum_name: &'static str,
            value: String,
        },
    }
}
