/*
    Generated by gesha command; DO NOT EDIT BY HAND!
*/
pub mod schemas {
    use serde::Deserialize;
    use serde::Serialize;

    #[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
    pub enum Symbols {
        #[serde(rename = "-")]
        Minus,
        #[serde(rename = "/*")]
        SlashAsterisk,
        #[serde(rename = "1+abc%3")]
        _1PlusAbcPercent3,
    }
}
