/*
    Generated by gesha command; DO NOT EDIT BY HAND!
*/
pub mod schemas {
    use serde::Deserialize;
    use serde::Serialize;

    /**
    Example of $ref to CAPITAL_CASE_TYPE
    */
    #[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
    pub struct Foo {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub foo1: Option<BAR_BAZ>,
    }

    #[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
    pub struct BarBaz {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub x1: Option<i64>,
    }
}
