/*
    Generated by gesha command; DO NOT EDIT BY HAND!
*/
pub mod schemas {
    use serde::Deserialize;
    use serde::Serialize;

    #[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
    pub struct Container {
        pub x0: ObjectSample,
        pub x1: NewTypeSample,
    }

    #[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
    pub struct ObjectSample {
        pub id: i64,
        pub name: String,
    }

    #[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
    pub struct NewTypeSample(String);
    impl From<String> for NewTypeSample {
        fn from(this: String) -> Self {
            Self(this)
        }
    }
    impl From<NewTypeSample> for String {
        fn from(this: NewTypeSample) -> Self {
            this.0
        }
    }
}
