use crate::v3_0::components::core::CoreShape;
use crate::v3_0::components::request_bodies::RequestBodiesShape;
use crate::v3_0::components::schemas::SchemasShape;
use crate::v3_0::components::ComponentsShape;
use crate::{Result, ToRustType};
use gesha_rust_types::{NonDocComments, SourceCode};
use openapi_types::v3_0::{ComponentsObject, Document};

impl ToRustType for Document {
    fn apply(self) -> Result<SourceCode> {
        let module = self
            .components
            .map(ToRustType::apply)
            .unwrap_or_else(|| Ok(SourceCode::empty()))?;

        Ok(module)
    }
}

impl ToRustType for ComponentsObject {
    fn apply(self) -> Result<SourceCode> {
        let shapes = ComponentsShape {
            schemas: SchemasShape::shape(self.schemas)?,
            request_bodies: RequestBodiesShape::shape(self.request_bodies)?,
            core: CoreShape::default(),
        };
        let preamble = Some(NonDocComments::block(
            "    Generated by gesha command; DO NOT EDIT BY HAND!",
        ));
        let mod_defs = shapes.into_mod_defs()?;
        Ok(SourceCode::new(preamble, mod_defs))
    }
}
