/*
    Generated by gesha command; DO NOT EDIT BY HAND!
*/
pub mod schemas {
    use serde::Deserialize;
    use serde::Serialize;

    #[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
    pub struct CamelCaseFields {
        #[serde(rename = "lowerCamelCase")]
        pub lower_camel_case: String,
        #[serde(rename = "UpperCamelCase")]
        pub upper_camel_case: String,
    }
}
